name: "Containers"
description: "Builds and optionally pushes container images"

inputs:
  container-registry-username:
    description: "Container registry username"
    required: false
  container-registry-password:
    description: "Container registry password"
    required: false
  wemogy-packages-token:
    description: "The token to use to authenticate with the wemogy-packages service"
    required: true
  version:
    description: "The version of the container image"
    required: true
  push:
    description: "Whether to push the container image to the registry"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Login to Docker Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v2
      with:
        username: wemogy
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
    - name: Build and push Container image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        context: .
        push: ${{ inputs.push }}
        tags: |
          wemogy/oauth2-mock:latest
          wemogy/oauth2-mock:${{ inputs.version }}
