name: "Containers"
description: "Builds and optionally pushes container images"

inputs:
  docker-hub-token:
    description: "Docke Hub Access Token"
    required: false
  version:
    description: "The version of the container image"
    required: true
  push:
    description: "Whether to push the container image to the registry"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Login to Docker Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v2
      with:
        username: wemogy
        password: ${{ inputs.docker-hub-token }}

    - name: Build and push Container image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        context: .
        push: ${{ inputs.push }}
        tags: |
          wemogy/oauth2-mock:latest
          wemogy/oauth2-mock:${{ inputs.version }}
