name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Check Pull Request Changes
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src: 'src/**'

  build-containers:
    name: Build Containers
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - uses: actions/checkout@v3
        if: needs.changes.outputs.src == 'true'
      - name: Build Containers
        if: needs.changes.outputs.src == 'true'
        uses: ./.github/actions/containers
        with:
          version: 0.0.0-test
          push: false
